server:
  port: 5000

spring:
  cloud:
    config:
      name: configserver
      server:
        git:
          uri: https://github.com/francislagueu/spring-micro-service
          search-paths: config-files*
